// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package repository

import (
	"context"
)

const getAllJobs = `-- name: GetAllJobs :many
SELECT id, slug, payload, priority, max_attempts, status, attempts, logs, errors, created_at, started_at, ended_at FROM jobs
`

func (q *Queries) GetAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Payload,
			&i.Priority,
			&i.MaxAttempts,
			&i.Status,
			&i.Attempts,
			&i.Logs,
			&i.Errors,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
