// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          uuid.UUID        `json:"id"`
	Slug        string           `json:"slug"`
	Payload     *json.RawMessage `json:"payload"`
	Priority    int32            `json:"priority"`
	MaxAttempts pgtype.Int4      `json:"max_attempts"`
	Status      string           `json:"status"`
	Attempts    int32            `json:"attempts"`
	Logs        []string         `json:"logs"`
	Errors      []string         `json:"errors"`
	CreatedAt   time.Time        `json:"created_at"`
	StartedAt   *time.Time       `json:"started_at"`
	EndedAt     *time.Time       `json:"ended_at"`
}
